repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [push]
        language: system
        entry: python -m isort src/**/*.py
        types: [python]

      - id: black
        name: black
        stages: [push]
        language: system
        entry: python -m black src
        types: [python]

      - id: flake8
        name: flake8
        stages: [push]
        language: system
        entry: pipenv -m flake8 .
        types: [python]

